config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'estimates/index'
  root to: "estimates#index"
  resources :estimates
  get '/estimate/:id', to: 'estimates#search'
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estimate_item.rb
class EstimateItem < ApplicationRecord
  has_many :estimate_products
  has_ancestry
end

app/models/estimate_product.rb
class EstimateProduct < ApplicationRecord
  with_options presence: true do
    validates :estimate_number, uniqueness: true
    validates :company_name
    validates :total_price
    validates :quantity
  end

  belongs_to :user
  belongs_to :estimate_item

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    # ひらがな、カタカナ、漢字のみ許可する
    validates :name, format: {with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: "is invalid. Input full-width characters."}
		# 半角英数字混合での入力が必須
    validates :password, format: { with: /\A(?=.*[a-zA-Z])(?=.*\d)/, message: "は半角英字と数字を含めてください" }
  end

  has_many :estimates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
   before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def index
  end

  def new
    @estimate_product = EstimateProduct.new
    @estimate_item = EstimateItem.new
    @parents = EstimateItem.all.order("id ASC").limit(3)
  end

  def search
    item = EstimateItem.find(params[:id])
    children_item = item.children
    render json:{ item: children_item }
  end


  def create
  @estimate_product = EstimateProduct.new(estimate_product_params)
    if @estimate_product.save
      post_pdf = EstimatePdf::PostPdf.new(@estimate_product, current_user)
      send_data post_pdf.render,
      filename: "#{@estimate_product.estimate_number}.pdf", # 作成されるファイル名を見積書番号に変更する
      type: 'application/pdf',
      disposition: 'inline' # 外すとダウンロード
    else
      render :new
    end
  end

  private

  def estimate_product_params
    params.require(:estimate_product).permit(:estimate_number, :company_name, :total_price, :quantity).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/estimates/index.html.erb
<%= render "shared/header" %>
<h1>Estimates#index</h1>
<p>Find me in app/views/estimates/index.html.erb</p>

app/views/estimates/new.html.erb
新規投稿
<div class="estimates-form">
  <%= form_with model: @estimate_product, url: estimates_path, local: true do |f| %>
    <div class="form-text">見積番号</div>
    <%= f.text_field :estimate_number %>

    <div class="form-text">会社名</div>
    <%= f.text_field :company_name %>

    <div class="form-text">見積金額</div>
    <%= f.text_field :total_price %>

    <div class="form-text">
    見積項目
      <div id="select-wrap">
        <%= f.collection_select :ancestry, @parents, :id, :summary, {include_blank: "---"}, {id: "parent-category" } %>
      </div>
    </div>

    
    <div class="form-text">数量</div>
    <%= f.text_field :quantity %>
    
    <div class="form-btn">
      <%= f.submit 'PDF作成' %>
    </div>
  <% end %>
      <button id="add-category-button">+ 追加</button>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Estimate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>

app/views/shared/_header.html.erb
  <header class="header">
      <div class="header__bar row">
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "マイページ", user_path(current_user), class: "user-name" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "新規作成", new_estimate_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

app/views/users/show.html.erb
マイページ